services:
  app-dev:
    build:
      context: .
      target: dev
      args:
        NEXT_PUBLIC_SANITY_PROJECT_ID: ${NEXT_PUBLIC_SANITY_PROJECT_ID}
        NEXT_PUBLIC_SANITY_DATASET: ${NEXT_PUBLIC_SANITY_DATASET:-production}
        NEXT_PUBLIC_SANITY_API_VERSION: ${NEXT_PUBLIC_SANITY_API_VERSION:-2024-02-12}
    container_name: aryaintaran-dev
    ports:
      - "3891:3891"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    env_file:
      - .env.local
    environment:
      GEMINI_API_KEY_FILE: /run/secrets/gemini_api_key
      GOOGLE_TRANSLATE_API_KEY_FILE: /run/secrets/google_translate_api_key
      NODE_OPTIONS: --dns-result-order=ipv4first
      SANITY_API_WRITE_TOKEN_FILE: /run/secrets/sanity_api_write_token
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    secrets:
      - gemini_api_key
      - google_translate_api_key
      - sanity_api_write_token
    command: npm run dev

  app-prod:
    build:
      context: .
      target: runner
      args:
        NEXT_PUBLIC_SANITY_PROJECT_ID: ${NEXT_PUBLIC_SANITY_PROJECT_ID}
        NEXT_PUBLIC_SANITY_DATASET: ${NEXT_PUBLIC_SANITY_DATASET:-production}
        NEXT_PUBLIC_SANITY_API_VERSION: ${NEXT_PUBLIC_SANITY_API_VERSION:-2024-02-12}
    container_name: aryaintaran-prod
    ports:
      - "3891:3891"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    env_file:
      - .env.local
    environment:
      GEMINI_API_KEY_FILE: /run/secrets/gemini_api_key
      GOOGLE_TRANSLATE_API_KEY_FILE: /run/secrets/google_translate_api_key
      NODE_OPTIONS: --dns-result-order=ipv4first
      SANITY_API_WRITE_TOKEN_FILE: /run/secrets/sanity_api_write_token
    secrets:
      - gemini_api_key
      - google_translate_api_key
      - sanity_api_write_token

secrets:
  gemini_api_key:
    file: ./.docker/secrets/gemini_api_key.txt
  google_translate_api_key:
    file: ./.docker/secrets/google_translate_api_key.txt
  sanity_api_write_token:
    file: ./.docker/secrets/sanity_api_write_token.txt
